<?php

namespace Wjbecker\ConnectwiseApiClient\Models\Service;

use Carbon\Carbon;
use Wjbecker\ConnectwiseApiClient\Models\BaseModel;

class Ticket extends BaseModel
{
    protected $casts = [
        '_info' => Metadata::class,
        'addressLine1' => 'string',
        'allowAllClientsPortalView' => 'boolean',
        'approved' => 'boolean',
        'automaticEmailCcFlag' => 'boolean',
        'automaticEmailContactFlag' => 'boolean',
        'automaticEmailResourceFlag' => 'boolean',
        'billExpenses' => 'string',
        'billProducts' => 'string',
        'billTime' => 'string',
        'billingMethod' => 'string',
        'board' => Reference::class,
        'city' => 'string',
        'closedBy' => 'string',
        'closedDate' => Carbon::class,
        'closedFlag' => 'boolean',
        'company' => Reference::class,
        'contact' => Reference::class,
        'contactName' => 'string',
        'contactPhoneNumber' => 'string',
        'country' => Reference::class,
        'currency' => 'array',
        'customFields' => 'array',
        'customerUpdatedFlag' => 'boolean',
        'dateResponded' => Carbon::class,
        'department' => Reference::class,
        'escalationLevel' => 'integer',
        'escalationStartDateUTC' => Carbon::class,
        'estimatedExpenseCost' => 'double',
        'estimatedExpenseRevenue' => 'double',
        'estimatedProductCost' => 'double',
        'estimatedProductRevenue' => 'double',
        'estimatedTimeCost' => 'double',
        'estimatedTimeRevenue' => 'double',
        'hasChildTicket' => 'boolean',
        'hasMergedChildTicketFlag' => 'boolean',
        'id' => 'integer',
        'impact' => 'string',
        'isInSla' => 'boolean',
        'location' => Reference::class,
        'minutesBeforeWaiting' => 'integer',
        'minutesWaiting' => 'integer',
        'mobileGuid' => 'string',
        'priority' => Reference::class,
        'recordType' => 'string',
        'requestForChangeFlag' => 'boolean',
        'resPlanMinutes' => 'integer',
        'resolutionHours' => 'double',
        'resolveMinutes' => 'integer',
        'resplanHours' => 'double',
        'resplanSkippedMinutes' => 'integer',
        'respondMinutes' => 'integer',
        'respondedBy' => 'string',
        'respondedHours' => 'double',
        'respondedSkippedMinutes' => 'integer',
        'serviceLocation' => Reference::class,
        'severity' => 'string',
        'site' => Reference::class,
        'siteName' => 'string',
        'sla' => Reference::class,
        'slaStatus' => 'string',
        'source' => Reference::class,
        'stateIdentifier' => 'string',
        'status' => Reference::class,
        'subBillingMethod' => 'string',
        'subType' => Reference::class,
        'summary' => 'string',
        'team' => Reference::class,
        'type' => Reference::class,
        'zip' => 'string',
    ];
}
